<h1>Dataset Preprocessing to Enable Application of Classical ML Models</h1>

In [1]:
import json
from timeit import default_timer

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
from model.model import build_preprocessing

In [4]:
# Load configuration file from json in the given folder
with open("config.json", "r") as config_file:
    config = json.load(config_file)

In [5]:
# Set up the list of gestures
with open(config["Paths"]["Gesture list"], "r") as gesture_list:
    gestures = gesture_list.readlines()[0].split(", ")

In [6]:
img_size = config["General parameters"]["Image size"]

In [7]:
train_images, test_images = tf.keras.preprocessing.image_dataset_from_directory("Data",
                                                                                labels="inferred",
                                                                                label_mode="int",
                                                                                class_names=gestures,
                                                                                color_mode="rgb",
                                                                                batch_size=128,
                                                                                image_size=(img_size,
                                                                                            img_size),
                                                                                shuffle=True,
                                                                                seed=45,
                                                                                validation_split=0.3,
                                                                                subset="both")

Found 36756 files belonging to 49 classes.
Using 25730 files for training.
Using 11026 files for validation.


In [8]:
# Set the default preprocessing pipeline if not specified
preprocessing_layers = config["Model"]["Default preprocessing"]
preprocessing_layers = "I,G,R"

# Build the preprocessing pipeline according to given instructions
img_size = 128
resize = tf.keras.layers.Resizing(img_size, img_size)
preprocessing = build_preprocessing(inp_shape=[img_size,
                                               img_size,
                                               3],
                                    instructions=preprocessing_layers,
                                    name="preprocessing_pipeline")

In [9]:
# Apply the same preprocessing steps as for the CNN but flatten the images
channels = 1 if "G" in preprocessing_layers else 3
train_images = train_images.map(lambda x, y: (tf.reshape(preprocessing(resize(x)), [-1, img_size ** 2 * channels]), y)).unbatch()
test_images = test_images.map(lambda x, y: (tf.reshape(preprocessing(resize(x)), [-1, img_size ** 2 * channels]), y)).unbatch()

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


In [10]:
# Convert the tf.data.Datasets to numpy arrays containing image & label per sample
train_images = np.array(list(train_images.as_numpy_iterator()), dtype=tuple)
test_images = np.array(list(test_images.as_numpy_iterator()), dtype=tuple)

In [11]:
# Extract the images and the labels separately
train_X, train_y = np.array([element[0] for element in train_images]), np.ravel(np.vstack([element[1] for element in train_images]))
test_X, test_y = np.array([element[0] for element in test_images]), np.ravel(np.vstack([element[1] for element in test_images]))

In [12]:
# Check memory consumption for the training dataset
print("Training dataset memory consumption: {:.1f}MB".format(train_X.nbytes / (1024 * 1024.0)))

Training dataset memory consumption: 1608.1MB


<h1>k-NN Gesture Classification</h1>

In [13]:
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import GridSearchCV

In [14]:
# Initialize and train the k-NN classifier with parameters obtained from grid search
knn = KNeighborsClassifier(n_neighbors=1,
                           p=1,
                           n_jobs=-1)
knn.fit(train_X, train_y)

KNeighborsClassifier(n_jobs=-1, n_neighbors=1, p=1)

In [15]:
# Evaluate the classifier on the test dataset
start = default_timer()
knn_predictions = knn.predict(test_X)

print("Time per gesture:", str(round((default_timer() - start) / (test_X.shape[0]), 5)) + " s")
print("Accuracy:", accuracy_score(test_y, knn_predictions))
print(classification_report(test_y,
                            knn_predictions,
                            target_names=gestures))

Time per gesture: 0.07603 s
Accuracy: 0.9832214765100671
              precision    recall  f1-score   support

     I index       0.99      1.00      0.99       217
          My       1.00      0.99      1.00       230
         You       0.99      1.00      0.99       231
        Your       1.00      0.97      0.99       236
          In       0.97      0.99      0.98       233
          To       1.00      0.98      0.99       222
        With       1.00      1.00      1.00       234
         Yes       1.00      0.99      1.00       222
          No       1.00      0.99      0.99       230
        Well       1.00      0.99      0.99       249
  I love you       1.00      0.97      0.99       229
    Oh I see       1.00      0.99      0.99       238
        Name       1.00      1.00      1.00       201
         Hug       1.00      1.00      1.00       231
    Internet       1.00      1.00      1.00       219
         Bus       1.00      1.00      1.00       213
       Money       0.99 

In [16]:
np.unique(knn_predictions, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]),
 array([220, 228, 233, 231, 236, 218, 233, 220, 229, 248, 223, 237, 202,
        230, 219, 212, 222, 237, 223, 229, 225, 228, 210, 217, 241, 242,
        219, 223, 219, 231, 240, 216, 257, 218, 215, 216, 218, 233, 225,
        222, 200, 222, 222, 222, 244, 208, 223, 231, 209], dtype=int64))

In [17]:
np.unique(test_y, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]),
 array([217, 230, 231, 236, 233, 222, 234, 222, 230, 249, 229, 238, 201,
        231, 219, 213, 220, 238, 223, 230, 226, 228, 211, 216, 234, 233,
        220, 221, 217, 238, 233, 220, 251, 217, 226, 213, 218, 228, 229,
        219, 202, 215, 215, 221, 249, 219, 220, 230, 211], dtype=int64))

<h1>Decision Tree Gesture Classification</h1>

In [18]:
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import GridSearchCV

In [19]:
# Initialize and train the Random Forest classifier with parameters obtained from grid search
rfc = RandomForestClassifier(n_estimators=100,
                             max_depth=55,
                             min_samples_split=5,
                             n_jobs=-1)
rfc.fit(train_X, train_y)

RandomForestClassifier(max_depth=55, min_samples_split=5, n_jobs=-1)

In [20]:
# Evaluate the classifier on the test dataset
start = default_timer()
rfc_predictions = rfc.predict(test_X)

print("Time per gesture:", str(round((default_timer() - start) / (test_X.shape[0]), 6)) + " s")
print("Accuracy:", accuracy_score(test_y, rfc_predictions))
print(classification_report(test_y,
                            rfc_predictions,
                            target_names=gestures))

Time per gesture: 0.000125 s
Accuracy: 0.9719753310357337
              precision    recall  f1-score   support

     I index       0.98      0.97      0.97       217
          My       0.98      0.96      0.97       230
         You       0.98      0.98      0.98       231
        Your       0.98      0.95      0.97       236
          In       0.93      0.98      0.95       233
          To       1.00      0.99      0.99       222
        With       0.98      0.97      0.97       234
         Yes       0.97      0.99      0.98       222
          No       0.99      0.95      0.97       230
        Well       0.97      1.00      0.98       249
  I love you       0.95      0.96      0.95       229
    Oh I see       0.98      0.96      0.97       238
        Name       0.98      1.00      0.99       201
         Hug       0.98      0.99      0.98       231
    Internet       0.99      0.99      0.99       219
         Bus       0.98      1.00      0.99       213
       Money       0.99

In [21]:
np.unique(rfc_predictions, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]),
 array([215, 226, 232, 228, 247, 220, 232, 225, 221, 258, 230, 233, 205,
        234, 218, 216, 223, 243, 223, 227, 225, 235, 212, 217, 237, 243,
        219, 225, 210, 237, 233, 214, 247, 221, 226, 201, 219, 230, 227,
        220, 212, 216, 216, 212, 236, 226, 221, 236, 197], dtype=int64))

In [22]:
np.unique(test_y, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]),
 array([217, 230, 231, 236, 233, 222, 234, 222, 230, 249, 229, 238, 201,
        231, 219, 213, 220, 238, 223, 230, 226, 228, 211, 216, 234, 233,
        220, 221, 217, 238, 233, 220, 251, 217, 226, 213, 218, 228, 229,
        219, 202, 215, 215, 221, 249, 219, 220, 230, 211], dtype=int64))

In [71]:
import os
import re
import warnings
import numpy as np
import cv2
import tensorflow as tf
from timeit import default_timer
from utils import create_rectangle, get_dictionary


def showcase_model(gesture_list, examples="Examples", predict=False,
                   model=None, translations="translations.txt", img_size=196):

    # The rectangle in the frame that is cropped from the web camera image
    # (one for torso location, one for fingerspelling location)
    rect_size = int(img_size * 1.25) + 4
    rect_torso = create_rectangle((225, 225), rect_size, rect_size)
    rect_fingerspell_1 = create_rectangle((50, 50), rect_size, rect_size)
    rect_fingerspell_2 = create_rectangle((350, 50), rect_size, rect_size)
    rect = rect_torso

    # Naive solution to allow looping through the gestures in prediction environment

    # Encapsulate the whole process to be able to close cameras in case of error
    try:

        cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

        # Establish the windows and place them accordingly
        cv2.namedWindow("Camera view")
        cv2.resizeWindow("Camera view", 800, 600)
        cv2.moveWindow("Camera view", 25, 150)

        cv2.namedWindow("Example")
        cv2.resizeWindow("Example", 640, 480)
        cv2.moveWindow("Example", 850, 230)

        lang = True  # To let the user change language, True stands for English, False for Czech
        rectangle_position = 0  # Which position of the rectangle to use
        pause_flag = False  # Enable the user to pause the process

        # Perform the data collecting process for each gesture in the given gesture list
        for gesture in gesture_list:

            # Initialize necessary variables (different per gesture)
            flag = 0  # To know when a new gesture is being taken for the first time
            exit_flag = 0  # To let the user end the process early by clicking the "Esc" key

            # Continue until the user terminates the process
            while True:
                ret, frame = cap.read()

                # Check validity and avoid mirroring if frame is present
                if not ret:
                    print("There has been a problem retrieving your frame")
                    print("Try adjusting the camera number in specification of cap (default 0)")
                    break
                frame = cv2.flip(frame, 1)

                # End the process for the current gesture in case the "q" key is hit
                key = cv2.waitKey(1)
                if key == ord("q"):
                    break

                # End the whole process in case the "Esc" key is hit
                if key == ord("\x1b"):
                    exit_flag = 1
                    break

                # Change language settings in case the "l" key is hit
                if key == ord("l"):
                    lang = not lang

                # Pause the process if the "p" key is hit
                if key == ord("p"):
                    pause_flag = not pause_flag

                # Change the rectangle position if the "spacebar" key is hit
                if key == ord(" "):
                    rectangle_position += 1
                    rect = [rect_torso, rect_fingerspell_1, rect_fingerspell_2][rectangle_position % 3]

                # Create rectangle cut
                frame_cut = frame[(rect[0][1] + 2):(rect[2][1] - 2),
                                  (rect[0][0] + 2):(rect[1][0] - 2)]
                frame_cut = cv2.resize(frame_cut, (img_size, img_size))

                # Adjust the color of the text and frame based on the current state
                # Green - running model prediction, Orange - model prediction is paused
                if pause_flag:
                    color = (0, 128, 255)
                else:
                    color = (0, 255, 0)

                # Live view with frame and text (colorcoded as specified above)
                cv2.rectangle(frame, rect[0], rect[3], color, 2)
                # Add information about prediction if expected, otherwise just show the name of the gesture
                if predict and not pause_flag:
                    pred_time_start = default_timer()
                    predict_frame = np.reshape(preprocessing(resize(frame_cut[None, :])).numpy()[0, :, :, 0], [1, -1])
                    prediction = model.predict(predict_frame)
                    #probability = prediction.max(axis=-1).round(2)
                    txt = gesture_list[prediction[0]]
                    pred_time = round(default_timer() - pred_time_start, 3)
                    if not lang:
                        txt = dictionary[txt]
                    #txt += " (" + str(probability[0]) + ")"

                    # Display average time per gesture
                    cv2.putText(frame, "TPG: " + str(pred_time) + " s", (5, 470),
                                cv2.FONT_HERSHEY_DUPLEX, 0.8, color, 2)
                else:
                    txt = gesture
                    if not lang:
                        txt = dictionary[txt]
                cv2.putText(frame, txt, (rect[0][0], rect[0][1] - 15),
                            cv2.FONT_HERSHEY_DUPLEX, 1, color, 2)
                cv2.imshow("Camera view", cv2.resize(frame, (800, 600)))

                # Show example on new gesture
                if not flag:
                    example = cv2.imread(f"{os.path.join(examples, gesture)}" + ".jpg")
                    cv2.imshow("Example", cv2.resize(example, (640, 480)))
                    flag = 1

            if exit_flag:
                break

    # Close the camera and all windows in case of unexpected fatality
    finally:
        cap.release()
        cv2.destroyAllWindows()

In [32]:
gestures = "I index, My, You, Your, In, To, With, Yes, No, Well, I love you, Oh I see, Name, Hug, Internet, Bus, Money, Work, Ask, Go, Look, Have, Correct, Want, A, B, C, D, E, F, G, H, I, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, N-A".split(", ")

In [72]:
showcase_model(gestures, predict=True, model=knn)